feat: add list_and_lock_head, delete_request_lock, prolong_request_lock methods
apify/apify-client-python pull request #129
Opened 2023-07-12 13:18 UTC by drobnikj

2023-07-13 11:13 UTC, jirimoravcik requested changes
I'd extend the tests, e.g. lock the requests for 10 seconds, then wait ~11 seconds and check if they were unlocked or something like that. Or maybe we'll do more extensive testing in the SDK so it's ok to have less tests here. We'll see what @fnesveda thinks.

2023-07-17 09:34 UTC, fnesveda requested changes
Nice! I like that you made integration tests for this, I'm sad that we don't have them for the rest of the client 😄 I just had some notes mostly to the docstrings.

And regarding Jirka's point - I'm not sure how complicated the tests need to be here, all the aspects of the platform features should be tested by the platform integration tests, not the client tests, so I think it's fine to just check if the API endpoints work and return what they should, without too many complicated tests.

2023-07-17 09:34 UTC, fnesveda commented on tests/integration/test_request_queue.py
> +class TestRequestQueueSync:
Some comments and a bit more formatting would be nice here

2023-07-17 09:34 UTC, fnesveda commented on src/apify_client/clients/resource_clients/request_queue.py
> +        """Retrieve the given number of first requests from the queue and locks them for the given time.
```suggestion
        """Retrieve a given number of unlocked requests from the beginning of the queue and lock them for a given time.
```

2023-07-17 09:34 UTC, fnesveda commented on src/apify_client/clients/resource_clients/request_queue.py
> +            lock_secs (int): How long the second request will be locked for
```suggestion
            lock_secs (int): How long the requests will be locked for, in seconds
```

2023-07-17 09:34 UTC, fnesveda commented on src/apify_client/clients/resource_clients/request_queue.py
> +            lock_secs (int): How long to prolong the lock
```suggestion
            lock_secs (int): By how much to prolong the lock, in seconds
```

2023-07-17 09:34 UTC, fnesveda commented on src/apify_client/clients/resource_clients/request_queue.py
> +            forefront (bool, optional): Whether to put the request in the beginning or the end of the queue after lock exppires
```suggestion
            forefront (bool, optional): Whether to put the request in the beginning or the end of the queue after lock expires
```

2023-07-17 09:34 UTC, fnesveda commented on src/apify_client/clients/resource_clients/request_queue.py
> +            forefront (bool, optional): Whether to put the request in the beginning or the end of the queue after lock deleted
```suggestion
            forefront (bool, optional): Whether to put the request in the beginning or the end of the queue after the lock is deleted
```

2023-07-17 09:34 UTC, fnesveda commented on src/apify_client/clients/resource_clients/request_queue.py
> +    def delete_request_lock(self, request_id: str, *, forefront: Optional[bool] = None) -> None:
We should have called this `unlock_request`, but too late

2023-07-18 09:48 UTC, jirimoravcik approved these changes

2023-07-18 10:21 UTC, fnesveda approved these changes

2023-07-18 10:22 UTC, fnesveda requested changes
I just realized, you should also bump the version and update the CHANGELOG.md

2023-07-18 10:58 UTC, jirimoravcik commented
> I just realized, you should also bump the version and update the CHANGELOG.md

how about we automate this going forward?

2023-07-18 11:01 UTC, fnesveda commented
> how about we automate this going forward?

I kind of like the versioning flexibility this gives us, plus we weren't making that many changes to these libraries for it to be worth investing the time into. But maybe there is some easy solution for this.

2023-07-19 07:55 UTC, fnesveda requested changes
You should bump the version to `1.3.0` in `pyproject.toml`, otherwise the publishing workflow will fail because `1.2.2` already exists.

2023-07-24 08:26 UTC, merged