feat: Added StoreCollectionClient for listing Actors in Apify store
apify/apify-client-python pull request #147
Opened 2023-09-04 14:12 UTC by drobnikj

2023-09-04 16:16 UTC, fnesveda requested changes
Cool, just one typo in the docstrings

2023-09-04 16:16 UTC, fnesveda commented on src/apify_client/clients/resource_clients/store_collection.py
> +            sort_be (str, optional): Specifies the field by which to sort the results.
```suggestion
            sort_by (str, optional): Specifies the field by which to sort the results.
```

2023-09-04 16:16 UTC, fnesveda commented on src/apify_client/clients/resource_clients/store_collection.py
> +            sort_be (str, optional): Specifies the field by which to sort the results.
```suggestion
            sort_by (str, optional): Specifies the field by which to sort the results.
```

2023-09-04 16:16 UTC, fnesveda commented on docs/docs.md
> +  * **sort_be** (`str`, *optional*) – Specifies the field by which to sort the results.
```suggestion
  * **sort_by** (`str`, *optional*) – Specifies the field by which to sort the results.
```

2023-09-04 16:16 UTC, fnesveda commented on docs/docs.md
> +  * **sort_be** (`str`, *optional*) – Specifies the field by which to sort the results.
```suggestion
  * **sort_by** (`str`, *optional*) – Specifies the field by which to sort the results.
```

2023-09-05 08:19 UTC, fnesveda approved these changes

2023-09-05 10:53 UTC, vdusek approved these changes
LGTM

2023-09-06 07:34 UTC, merged