feat: Add run, build delete to client
apify/apify-client-python pull request #152
Opened 2023-10-05 09:04 UTC by Jkuzz

Resolves https://github.com/apify/apify-core/issues/12463
waiting for https://github.com/apify/apify-core/pull/12531, https://github.com/apify/apify-core/pull/12504

2023-10-05 12:18 UTC, jirimoravcik approved these changes

2023-10-10 07:57 UTC, fnesveda requested changes
Cool! Please also bump the version in `pyproject.toml` to `1.5.0` and describe the changes in `CHANGELOG.md`, otherwise the CI will fail after you merge to `master`.

Check https://github.com/apify/apify-client-python/blob/master/CONTRIBUTING.md#beta-release-checklist, it describes the needed steps. We should improve the CI so it checks them automatically, I'll take a look at it someday.

2023-10-10 08:53 UTC, fnesveda approved these changes
Cool! One last tiny suggestion

2023-10-10 08:53 UTC, fnesveda commented on CHANGELOG.md
>  -----------------------------------------------
I suppose you can remove these two lines, since `1.4.2` will never be released in the end

2023-10-10 09:09 UTC, merged