docs: Added new getting started page
apify/apify-client-python pull request #232
Opened 2024-05-29 15:23 UTC by jbartadev

I tried to do the same thing as we did for the JS client [here](https://github.com/apify/apify-client-js/pull/542) but for Python.

The goal is to improve onboarding (adaptation) for using our API (in Python in this case)

<img width="1768" alt="Snímek obrazovky 2024-05-29 v 17 17 17" src="https://github.com/apify/apify-client-python/assets/45016873/bbb4a7ae-5542-43a5-9ae9-182715cce88c">

2024-05-29 16:16 UTC, vdusek requested changes
Nice, thanks!

I have a few code style suggestions to share.

On top of that, one more thing... It's not a requirement, more a personal preference. In many places I'd prefer not to chain so many calls into one command. Breaking it down to more separate commands can make it more understandable for users. Also when you want to transform such long-chained command into async command, you will end up with multiple awaits in one command. Which is not goood.

For example, instead of writing:

```python
from apify_client import ApifyClient

apify_client = ApifyClient('MY-APIFY-TOKEN')

# Lists items from the Actor's dataset
dataset_items = apify_client.dataset('daset-id').list_items().items
```

I'd rather use something like:
```python
from apify_client import ApifyClient

apify_client = ApifyClient('MY-APIFY-TOKEN')

# Get a dataset client
dataset_client = apify_client.dataset('daset-id')

# Lists items from the Actor's dataset
dataset_items = dataset_client.list_items().items
```

2024-05-29 16:16 UTC, vdusek commented on docs/index.md
> +    )
fix indentation

```suggestion
apify_client = ApifyClient(
    token='MY-APIFY-TOKEN',
    max_retries=8,
    min_delay_between_retries_millis=500, # 0.5s
    timeout_secs=360, # 6 mins
)
```

2024-05-29 16:16 UTC, vdusek commented on docs/index.md
> +```
unify quotes

```suggestion
while True:
    response = dataset_client.list_items(limit=limit, offset=offset)
    items = response.items
    total = response.total
    
    print(f'Fetched {len(items)} items')

    # Merge new items with other already loaded items
    all_items.extend(items)

    # If there are no more items to fetch, exit the loading
    if offset + limit >= total:
        break

    offset += limit

print(f'Overall fetched {len(all_items)} items')
```

2024-05-30 07:51 UTC, jbartadev commented
@vdusek Thanks Vláďo for the suggested improvements! I added a couple of simplifications for the code examples (removed unnecessary chaining). Please let me know if it's ok now

2024-05-30 08:48 UTC, vdusek approved these changes
just one nitpick, otherwise LGTM, thanks :slightly_smiling_face:

2024-05-30 08:48 UTC, vdusek commented on docs/index.md
> +# Resource clients accept an ID of the resource.
probably the only comment with dot in the end

```suggestion
# Resource clients accept an ID of the resource
```

2024-05-30 09:08 UTC, HonzaTuron approved these changes

2024-05-30 10:52 UTC, TC-MO approved these changes
LGTM

2024-05-30 11:44 UTC, merged