Add subclient for querying all builds for a user
apify/apify-client-python pull request #26
Opened 2021-01-15 08:44 UTC by mhamas

Note that this client queries for builds of **a user**, not a particular actor.

2021-01-15 18:56 UTC, fnesveda requested changes

2021-01-15 18:56 UTC, fnesveda commented on src/apify_client/clients/resource_clients/build_collection.py
> +    def list(self, *, limit: Optional[int] = None, offset: Optional[int] = None, desc: Optional[bool] = None) -> Dict:
Could you document the args as well? D417 didn't fire here again for some reason.

2021-01-17 23:49 UTC, Equidem approved these changes

2021-01-18 11:31 UTC, fnesveda approved these changes

2021-01-22 13:24 UTC, merged