Catch up to JS client
apify/apify-client-python pull request #85
Opened 2022-11-22 13:24 UTC by jirimoravcik

2022-11-30 10:40 UTC, fnesveda requested changes
Nice, looks great! I just had a couple of small comments.

2022-11-30 14:45 UTC, fnesveda requested changes
Nice! Oh and one more thing, can you add the changes to changelog, please?

2022-12-01 09:53 UTC, mhamas approved these changes
looks good to me, thanks

2022-12-01 15:23 UTC, fnesveda requested changes
Almost perfect, last nitpick now 😄

2022-12-01 15:23 UTC, fnesveda commented on CHANGELOG.md
> +- added support for `schema` parameter in `getOrCreate` method for datasets and key-value stores
We use `snake_case` here 🙂 
```suggestion
- added support for `schema` parameter in `get_or_create` method for datasets and key-value stores
```

2022-12-01 19:01 UTC, jirimoravcik commented
> Almost perfect, last nitpick now 😄

yes, i'm struggling with snake case a lot atm :D

2022-12-02 08:15 UTC, fnesveda approved these changes

2022-12-02 10:24 UTC, merged